### PR TITLE
Support async functions

### PR DESCRIPTION
**Pull request by aheckmann**
See #5 

**TODO**

- [x] node 7.6+ requirement
- [x] finish + publish await-busboy and use here
- [x] not backward compatibility with generators
- [x] koa@2 required

### CODE REVIEW

**Comment by reyawn** [comment]
@aheckmann Node 7.6.0 was released - async/await without a flag! :tada:

**Comment by paul42** [comment]
can I pull this branch from npm by using koa-joi-router@next?

**Comment by aheckmann** [comment]
Made some progress: https://github.com/aheckmann/await-busboy

**Comment by aheckmann** [comment]
Looks like just code coverage issues remaining. Please test this out / code review / provide feedback.

**Comment by paul42** [comment]
Question: is the continueOnError:true working in route validation? I might be doing it wrong, but even when I swap it to true I get an issue where it appears to send back a 400 and not hit the handler.

overly rough example repo: https://github.com/paul42/koa-joi-router-example/blob/master/lib/routes/postHello.js

route I was trying: POST to localhost:3000/hello
sending in correct json it hits the handler, sneding in the incorrect json does not hit the handler, despite continueOnError: true

I'm more than willing to take a very inexperienced stab at a pr if you could point me in the right direction and show me where the continue on error stuff lies?

Thanks in advance,
Paul

**Comment by aheckmann** [comment]
@paul42 seems to be ok.

- it's implemented [here](https://github.com/koajs/joi-router/blob/await/joi-router.js#L291-L292)
- the tests are [here](https://github.com/koajs/joi-router/blob/await/test/index.js#L373-L403) - just search for `continueOnError`

**Comment by paul42** [comment]
@aheckmann you were 100% correct, user error over here 😅 I'm loving the library btw. it just makes more sense than anything else. 

btw, is there an easy way to dig into the .Joi's settings and wrench the 'abort early' to false? 
https://github.com/hapijs/joi/blob/v9.0.4/API.md#validatevalue-schema-options-callback
I'm lazy and want to show my users all the errors they've made so they don't fix them one at a time.

**Comment by aheckmann** [comment]
@paul42 not currently but sounds like a good idea.  We'll just need to add support for joi options and pass them here: https://github.com/koajs/joi-router/blob/master/joi-router.js#L393

**Comment by aheckmann** [comment]
5.0.0 is out

**Pull request merged**
