### PR TITLE
Test and Fixes for #6 - Dates in querystring become empty strings

### PR DESCRIPTION
**Pull request by toadzky**
Repost of #9

### CODE REVIEW

**Comment by toadzky** [comment]
sorry it took me so long to resolve the conflict.

**Comment by aheckmann** [comment]
Does it make sense to test the remaining types as well? Array, function, binary, object

What about arrays of dates and other types? 
Objects with date properties etc? 
Or must querystring be flat?

**Comment by aheckmann** [comment]
Also, does koa itself have a bug here?

**Comment by toadzky** [comment]
the actual problem, iirc, is that koa uses node's `querystring` instead of `qs` so when it saves the querystring back after processing it, it converts everything that is not a primitive to empty string (https://github.com/nodejs/node/blob/master/lib/querystring.js#L150-L158). based on querystring's stringify method, it looks like arrays of objects might be converted into an array of empty strings. 

basically, anything that isn't a primitive or an array of primitives in a querystring will get lost and booleans become strings. my fix basically tracks fields that are boolean or dates and overwrites the `request.query` method from koa and reparses the values the first time they are requested. it could probably be more generic and handle anything that wasn't an primitive or array of primitive, but dates and booleans were my particular pain point at the time.

**Comment by pebble-solano** [comment]
can you open a ticket with koa and link it here? I'm interested in seeing
if they'd accept the patch there before falling back to the work-arounds
here.

On Wed, Feb 3, 2016 at 8:14 AM David Harris <notifications@github.com>
wrote:

> the actual problem, iirc, is that koa uses node's querystring instead of
> qs so when it saves the querystring back after processing it, it converts
> everything that is not a primitive to empty string (
> https://github.com/nodejs/node/blob/master/lib/querystring.js#L150-L158).
> based on querystring's stringify method, it looks like arrays of objects
> might be converted into an array of empty strings.
>
> basically, anything that isn't a primitive or an array of primitives in a
> querystring will get lost and booleans become strings. my fix basically
> tracks fields that are boolean or dates and overwrites the request.query
> method from koa and reparses the values the first time they are requested.
> it could probably be more generic and handle anything that wasn't an
> primitive or array of primitive, but dates and booleans were my particular
> pain point at the time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pebble/koa-joi-router/pull/12#issuecomment-179318603>.
>
-- 
Aaron Heckmann
Web Development Lead :: Pebble
https://github.com/aheckmann
https://twitter.com/aaronheckmann

**Comment by aheckmann** [comment]
could you open a ticket with koa and link it here? I'm interested in seeing
if they'd accept the patch there before falling back to the work-arounds
here.

**Comment by toadzky** [comment]
I'm going to test if using the `koa-qs` module that replaces the querystring handling with qs fixes the issue first. I didn't even consider it earlier.

**Comment by aheckmann** [comment]
closed due to inactivity

**Pull request closed without merging**
