### PR TITLE
Migrate from `@hapi/joi` to `joi`

### LINKED ISSUE #99: Update Joi to version 17
Please update Joi to version 17.

### PR DESCRIPTION
**Pull request by 3imed-jaberi**
`@hapi/joi` has been deprecated. as you can see [here](https://www.npmjs.com/package/@hapi/joi).

fix #99 ++ #103

### CODE REVIEW

**Review by AlexandreLoub — APPROVED** [review]

**Comment by 3imed-jaberi** [comment]
@aheckmann, can you take a look here!

**Review by NurMarvin — APPROVED** [review]

**Comment by 3imed-jaberi** [comment]
ping @niftylettuce  @dead-horse @jonathanong

**Comment by niftylettuce** [comment]
Just pinged for npm access

**Comment by 3imed-jaberi** [comment]
@niftylettuce, Meanwhile you can close this PRs #103, #105 and merge this also #112 and you can take look here #108 😅!

**Comment by niftylettuce** [comment]
done

**Comment by niftylettuce** [comment]
seems like a test is failing @3imed-jaberi 

```sh
  312 passing (3s)
  1 failing

  1) koa-joi-router
       validation
         of body
           when invalid data is submitted
             and validate.continueOnError is true
               and an error is thrown in route
                 does not catch it:
     Error: expected 'child "name" fails because ["name" length must be at least 10 characters long]' response body, got '"name" length must be at least 10 characters long'
      at error (node_modules/supertest/lib/test.js:301:13)
      at Test._assertBody (node_modules/supertest/lib/test.js:218:14)
      at Test._assertFunction (node_modules/supertest/lib/test.js:283:11)
      at Test.assert (node_modules/supertest/lib/test.js:173:18)
      at Server.localAssert (node_modules/supertest/lib/test.js:131:12)
      at emitCloseNT (net.js:1655:8)
      at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

**Comment by 3imed-jaberi** [comment]
@niftylettuce, I think the case here is fine because all tests are passed both locally and in the CI of this PR. I will check every thing in the project and see what I can do (maybe the merge operation with others PRs) ..

**Comment by niftylettuce** [comment]
v7.0.0 released https://github.com/koajs/joi-router/releases/tag/v7.0.0

**Pull request merged**
