### PR TITLE
joi 9.0.0; updated test expect string

### PR DESCRIPTION
**Pull request by eizzo**
Test expected against old error string; updated. Set Joi version to 9.0.0.

### CODE REVIEW

**Comment by aheckmann** [comment]
coveralls is crazy??

**Comment by aheckmann** [comment]
ran locally. fixed the test. coverage was back to normal. merged manually. it's on master now.

**Comment by eizzo** [comment]
thank you!

**Comment by aheckmann-pebble** [comment]
thank you! also opened https://github.com/koajs/joi-router/pull/23

**Pull request closed without merging**
