### PR TITLE
chore: replace koa-router to @koa/router

### PR DESCRIPTION
**Pull request by booxood**
koa-router@7.4.0 -> @koa/router@8.0.0

### CODE REVIEW

**Comment by adrianhopebailie** [comment]
@aheckmann this seems like a good idea, no?

**Comment by swarthy** [comment]
Also @hapijs/joi@15.0.0 is deprecated, it could be nice to update joi version to latest

**Comment by yuriploc** [comment]
> Also @hapijs/joi@15.0.0 is deprecated, it could be nice to update joi version to latest

This would require more effort than migrating to the `@koa` namespace. Shouldn't it be in another PR?

**Comment by swarthy** [comment]
> > Also @hapijs/joi@15.0.0 is deprecated, it could be nice to update joi version to latest
> 
> This would require more effort than migrating to the `@koa` namespace. Shouldn't it be in another PR?

update 15.0.0 -> 15.1.1 doesn't seems like a breaking change
anyway #93

**Comment by aheckmann** [comment]
closing. `koa/router` addressed in bd7474e19be4f8fffbbcb6639cda15384f35fa42.

**Pull request closed without merging**
